---
- name: Install HTTP server
  hosts: g1
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present
    when: ansible distribution == "Amazon"

  - name: start HTTPD
    service:
      name: httpd
      state: started
    when: ansible distribution == "Amazon"

  - name: enable HTTPD
    service:
      name: httpd
      enabled: yes   
    when: ansible distribution == "Amazon"

  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when: ansible distribution == "Ubuntu"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible distribution == "Ubuntu"

  - name: enable apache2
    service:
      name: apache2
      enabled: yes    
    when: ansible distribution == "Ubuntu"
...
