---
- name: Variable Demo
  hosts: g1
  become: yes
  vars:
    myusername: Vickysurest

  tasks:
  - name: Update dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/static.html

...