---
  - name: Update static page
    copy:
      src: static.html
      dest: /var/www/html/static.html

  - name: Update static page
    template:
      src: dynamic.j2
      dest: /var/www/html/static.html


...